export const roomTypes = [
  'Standard Room',
  'Single Room',
  'Double Room',
  'Suite',
  'Deluxe Room',
  'Executive Room',
  'Family Room',
  'Penthouse',
  'Studio',
];
export const bedTypes = [
  'King Size Bed',
  'Queen Size Bed',
  'Double Bed',
  'Single Bed',
  'Twin Beds',
  'Sofa Bed',
  'Rollaway Bed',
  'Bunk Beds',
  'Extra Large Bed',
];

export const allAmenities = [
  { name: 'Pool', id: 'poolCheckbox' },
  { name: 'Fitness Center', id: 'fitnessCheckbox' },
  { name: 'Spa', id: 'spaCheckbox' },
  { name: 'Restaurant', id: 'restaurantCheckbox' },
  { name: 'Conference Room', id: 'conferenceRoomCheckbox' },
  { name: 'Wi-Fi Paid', id: 'wifiCheckbox' },
  { name: 'Parking', id: 'parkingCheckbox' },
  { name: 'Pet Friendly', id: 'petFriendlyCheckbox' },
  { name: 'Laundry Service', id: 'laundryCheckbox' },
  { name: 'Business Center', id: 'businessCenterCheckbox' },
  { name: 'Shuttle Service', id: 'shuttleCheckbox' },
  { name: '24-Hour Front Desk', id: 'frontDeskCheckbox' },
  { name: 'Gym', id: 'gymCheckbox' },
  { name: 'Lounge Area', id: 'loungeCheckbox' },
  { name: 'Free Wi-Fi', id: 'freeWifiCheckbox' },
  { name: 'TV', id: 'tvCheckbox' },
  { name: 'Air Conditioning', id: 'airConditioningCheckbox' },
  { name: 'Coffee Maker', id: 'coffeeMakerCheckbox' },
  { name: 'Balcony', id: 'balconyCheckbox' },
  { name: 'Jacuzzi', id: 'jacuzziCheckbox' },
  { name: 'Barbecue Area', id: 'barbecueCheckbox' },
  { name: 'Room Service', id: 'roomServiceCheckbox' },
  { name: 'Ensuite Bathroom', id: 'ensuiteBathroomCheckbox' },
  { name: 'Telephone', id: 'telephoneCheckbox' },
  { name: 'Daily Housekeeping', id: 'dailyHousekeepingCheckbox' },
  { name: 'Complimentary Toiletries', id: 'toiletriesCheckbox' },
  { name: 'Closet', id: 'closetCheckbox' },
  { name: 'Iron and Ironing Board', id: 'ironCheckbox' },
  { name: 'Hair Dryer', id: 'hairDryerCheckbox' },
  { name: 'Safe', id: 'safeCheckbox' },
  { name: 'Mini Fridge', id: 'miniFridgeCheckbox' },
  { name: 'Microwave', id: 'microwaveCheckbox' },
  { name: 'Desk', id: 'deskCheckbox' },
  { name: 'Wake-up Service', id: 'wakeUpServiceCheckbox' },
  { name: 'Heating', id: 'heatingCheckbox' },
  { name: 'Cable Channels', id: 'cableChannelsCheckbox' },
  { name: 'Non-Smoking Rooms', id: 'nonSmokingCheckbox' },
  { name: 'Soundproof Rooms', id: 'soundproofCheckbox' },
  { name: 'Family Rooms', id: 'familyRoomsCheckbox' },
  { name: 'Elevator', id: 'elevatorCheckbox' },
  { name: 'Wheelchair Accessible', id: 'wheelchairAccessibleCheckbox' },
  { name: 'Airport Shuttle', id: 'airportShuttleCheckbox' },
  { name: 'Concierge Service', id: 'conciergeCheckbox' },
  { name: 'Valet Parking', id: 'valetParkingCheckbox' },
  { name: 'Currency Exchange', id: 'currencyExchangeCheckbox' },
  { name: 'ATM on Site', id: 'atmCheckbox' },
  { name: 'Gift Shop', id: 'giftShopCheckbox' },
  { name: 'Express Check-in/Check-out', id: 'expressCheckInCheckbox' },
  { name: 'Tour Desk', id: 'tourDeskCheckbox' },
  { name: 'Ticket Service', id: 'ticketServiceCheckbox' },
  { name: 'Luggage Storage', id: 'luggageStorageCheckbox' },
  { name: 'Library', id: 'libraryCheckbox' },
  { name: 'Sun Terrace', id: 'sunTerraceCheckbox' },
  { name: 'Garden', id: 'gardenCheckbox' },
  { name: 'Picnic Area', id: 'picnicAreaCheckbox' },
  { name: 'Outdoor Furniture', id: 'outdoorFurnitureCheckbox' },
  { name: 'Terrace', id: 'terraceCheckbox' },
  { name: 'BBQ Facilities', id: 'bbqFacilitiesCheckbox' },
  { name: 'Vending Machine Drinks', id: 'vendingMachineDrinksCheckbox' },
  { name: 'Vending Machine Snacks', id: 'vendingMachineSnacksCheckbox' },
  { name: 'Special Diet Menus on request', id: 'specialDietMenusCheckbox' },
  { name: 'Packed Lunches', id: 'packedLunchesCheckbox' },
  { name: 'Bar', id: 'barCheckbox' },
  { name: 'Wine Champagne', id: 'wineChampagneCheckbox' },
  { name: 'Bottle of Water', id: 'bottleOfWaterCheckbox' },
  { name: 'Chocolate Cookies', id: 'chocolateCookiesCheckbox' },
  { name: 'Kid-Friendly Buffet', id: 'kidFriendlyBuffetCheckbox' },
  { name: 'Kid Meals', id: 'kidMealsCheckbox' },
  { name: 'Breakfast in the Room', id: 'breakfastInRoomCheckbox' },
  { name: 'Restaurant Buffet', id: 'restaurantBuffetCheckbox' },
  { name: 'Snack Bar', id: 'snackBarCheckbox' },
  { name: 'Fruit', id: 'fruitCheckbox' },
  { name: 'Buffet Breakfast', id: 'buffetBreakfastCheckbox' },
  { name: 'Continental Breakfast', id: 'continentalBreakfastCheckbox' },
  { name: 'Gluten-Free Options', id: 'glutenFreeOptionsCheckbox' },
  { name: 'Vegetarian Options', id: 'vegetarianOptionsCheckbox' },
  { name: 'Vegan Options', id: 'veganOptionsCheckbox' },
  { name: 'Halal Options', id: 'halalOptionsCheckbox' },
  { name: 'Kosher Options', id: 'kosherOptionsCheckbox' },
  { name: 'Allergy-Free Room', id: 'allergyFreeRoomCheckbox' },
  { name: 'Designated Smoking Area', id: 'smokingAreaCheckbox' },
  { name: 'Non-Smoking Throughout', id: 'nonSmokingThroughoutCheckbox' },
  { name: 'Kitchen', id: 'kitchen' },
];
export const paths = [
  { title: 'Dashboard', path: '/dashboard' },
  { title: 'Messenger', path: '/messenger' },
  { title: 'Your Bookings', path: '/your-bookings' },
  { title: 'Bookings', path: '/all-bookings' },
  { title: 'Hotels', path: '/hotels' },
  { title: 'Complaints', path: '/your-complaints' },
  { title: 'Your Hotel', path: '/your-hotels' },
  { title: 'Set Monthly Price', path: '/hotels/monthly-price' },
  { title: 'Manage Coupons', path: '/apply-pms-coupon' },
  { title: 'Complaints', path: '/complaints' },
  { title: 'Reviews', path: '/all-reviews' },
  { title: 'Manage users', path: '/all-users' },
  { title: 'Bulk Operation', path: '/bulk-data-processing' },
  { title: 'Add travel location', path: '/add-travel-location' },
  { title: 'Availability', path: '/hotels/availability' },
  { title: 'Set Month', path: '/hotels/monthly-price' },
  { title: 'Change banner', path: '/change-banner' },
  { title: 'Manage Coupons', path: '/apply-coupon' },
  { title: 'Push notification', path: '/send-notification-to-all' },
];
