import { role } from "./util";

export const roomTypes = ['Single Room', 'Double Room', 'Suite', 'Deluxe Room', 'Executive Room', 'Family Room', 'Penthouse', 'Studio'];
export const bedTypes = [
    'King Size Bed',
    'Queen Size Bed',
    'Double Bed',
    'Single Bed',
    'Twin Beds',
    'Sofa Bed',
    'Rollaway Bed',
    'Bunk Beds',
    'Extra Large Bed',
];

export const allAmenities = [
    { name: 'Pool', id: 'poolCheckbox' },
    { name: 'Fitness Center', id: 'fitnessCheckbox' },
    { name: 'Spa', id: 'spaCheckbox' },
    { name: 'Restaurant', id: 'restaurantCheckbox' },
    { name: 'Conference Room', id: 'conferenceRoomCheckbox' },
    { name: 'Wi-Fi Paid', id: 'wifiCheckbox' },
    { name: 'Parking', id: 'parkingCheckbox' },
    { name: 'Pet Friendly', id: 'petFriendlyCheckbox' },
    { name: 'Laundry Service', id: 'laundryCheckbox' },
    { name: 'Business Center', id: 'businessCenterCheckbox' },
    { name: 'Shuttle Service', id: 'shuttleCheckbox' },
    { name: '24-Hour Front Desk', id: 'frontDeskCheckbox' },
    { name: 'Gym', id: 'gymCheckbox' },
    { name: 'Lounge Area', id: 'loungeCheckbox' },
    { name: 'Free Wi-Fi', id: 'freeWifiCheckbox' },
    { name: 'TV', id: 'tvCheckbox' },
    { name: 'Air Conditioning', id: 'airConditioningCheckbox' },
    { name: 'Coffee Maker', id: 'coffeeMakerCheckbox' },
    { name: 'Balcony', id: 'balconyCheckbox' },
    { name: 'Jacuzzi', id: 'jacuzziCheckbox' },
    { name: 'Barbecue Area', id: 'barbecueCheckbox' },
    { name: 'Room Service', id: 'roomServiceCheckbox' },
    { name: 'Ensuite Bathroom', id: 'ensuiteBathroomCheckbox' },
    { name: 'Telephone', id: 'telephoneCheckbox' },
    { name: 'Daily Housekeeping', id: 'dailyHousekeepingCheckbox' },
    { name: 'Complimentary Toiletries', id: 'toiletriesCheckbox' },
    { name: 'Closet', id: 'closetCheckbox' },
    { name: 'Iron and Ironing Board', id: 'ironCheckbox' },
    { name: 'Hair Dryer', id: 'hairDryerCheckbox' },
    { name: 'Safe', id: 'safeCheckbox' },
    { name: 'Mini Fridge', id: 'miniFridgeCheckbox' },
    { name: 'Microwave', id: 'microwaveCheckbox' },
    { name: 'Desk', id: 'deskCheckbox' },
    { name: 'Wake-up Service', id: 'wakeUpServiceCheckbox' },
    { name: 'Heating', id: 'heatingCheckbox' },
    { name: 'Cable Channels', id: 'cableChannelsCheckbox' },
    { name: 'Non-Smoking Rooms', id: 'nonSmokingCheckbox' },
    { name: 'Soundproof Rooms', id: 'soundproofCheckbox' },
    { name: 'Family Rooms', id: 'familyRoomsCheckbox' },
    { name: 'Elevator', id: 'elevatorCheckbox' },
    { name: 'Wheelchair Accessible', id: 'wheelchairAccessibleCheckbox' },
    { name: 'Airport Shuttle', id: 'airportShuttleCheckbox' },
    { name: 'Concierge Service', id: 'conciergeCheckbox' },
    { name: 'Valet Parking', id: 'valetParkingCheckbox' },
    { name: 'Currency Exchange', id: 'currencyExchangeCheckbox' },
    { name: 'ATM on Site', id: 'atmCheckbox' },
    { name: 'Gift Shop', id: 'giftShopCheckbox' },
    { name: 'Express Check-in/Check-out', id: 'expressCheckInCheckbox' },
    { name: 'Tour Desk', id: 'tourDeskCheckbox' },
    { name: 'Ticket Service', id: 'ticketServiceCheckbox' },
    { name: 'Luggage Storage', id: 'luggageStorageCheckbox' },
    { name: 'Library', id: 'libraryCheckbox' },
    { name: 'Sun Terrace', id: 'sunTerraceCheckbox' },
    { name: 'Garden', id: 'gardenCheckbox' },
    { name: 'Picnic Area', id: 'picnicAreaCheckbox' },
    { name: 'Outdoor Furniture', id: 'outdoorFurnitureCheckbox' },
    { name: 'Terrace', id: 'terraceCheckbox' },
    { name: 'BBQ Facilities', id: 'bbqFacilitiesCheckbox' },
    { name: 'Vending Machine Drinks', id: 'vendingMachineDrinksCheckbox' },
    { name: 'Vending Machine Snacks', id: 'vendingMachineSnacksCheckbox' },
    { name: 'Special Diet Menus on request', id: 'specialDietMenusCheckbox' },
    { name: 'Packed Lunches', id: 'packedLunchesCheckbox' },
    { name: 'Bar', id: 'barCheckbox' },
    { name: 'Wine Champagne', id: 'wineChampagneCheckbox' },
    { name: 'Bottle of Water', id: 'bottleOfWaterCheckbox' },
    { name: 'Chocolate Cookies', id: 'chocolateCookiesCheckbox' },
    { name: 'Kid-Friendly Buffet', id: 'kidFriendlyBuffetCheckbox' },
    { name: 'Kid Meals', id: 'kidMealsCheckbox' },
    { name: 'Breakfast in the Room', id: 'breakfastInRoomCheckbox' },
    { name: 'Restaurant Buffet', id: 'restaurantBuffetCheckbox' },
    { name: 'Snack Bar', id: 'snackBarCheckbox' },
    { name: 'Fruit', id: 'fruitCheckbox' },
    { name: 'Buffet Breakfast', id: 'buffetBreakfastCheckbox' },
    { name: 'Continental Breakfast', id: 'continentalBreakfastCheckbox' },
    { name: 'Gluten-Free Options', id: 'glutenFreeOptionsCheckbox' },
    { name: 'Vegetarian Options', id: 'vegetarianOptionsCheckbox' },
    { name: 'Vegan Options', id: 'veganOptionsCheckbox' },
    { name: 'Halal Options', id: 'halalOptionsCheckbox' },
    { name: 'Kosher Options', id: 'kosherOptionsCheckbox' },
    { name: 'Allergy-Free Room', id: 'allergyFreeRoomCheckbox' },
    { name: 'Designated Smoking Area', id: 'smokingAreaCheckbox' },
    { name: 'Non-Smoking Throughout', id: 'nonSmokingThroughoutCheckbox' },
    { name: 'Kitchen', id: 'kitchen' },
];
export const paths = [
    { title: 'Dashboard', path: '/dashboard', role: 'PMS' },
    { title: 'Messenger', path: '/messenger', role: 'PMS' },
    { title: 'Cars', path: '/your-cars', role: 'TMS' },
    { title: 'My Ride', path: '/your-car-details/owner-car', role: 'TMS' },
    { title: 'Add Tour', path: '/add-tour-data', role: 'TMS' },
    { title: 'Tour List', path: '/tour-list', role: 'TMS' },
    { title: 'Car Owner', path: '/cars-owner', role: 'TMS' },
    { title: 'Add Car', path: '/add-a-car', role: 'TMS' },
    { title: 'Add Owner', path: '/add-an-car-owner', role: 'TMS' },
    { title: 'Your Bookings', path: '/your-bookings', role: 'PMS' },
    { title: 'Bookings', path: '/all-bookings', role: 'Admin' },
    { title: 'Create Booking', path: '/booking-creation', role: 'Admin' },
    { title: 'Hotels', path: '/hotels', role: 'Admin' },
    { title: 'Manage Coupons', path: '/apply-pms-coupon', role: 'PMS' },
    { title: 'Your Complaints', path: '/your-complaints', role: 'PMS' },
    { title: 'Your Hotel', path: '/your-hotels', role: 'PMS' },
    { title: 'Set Monthly Price', path: '/hotels/monthly-price', role: 'PMS' },
    { title: 'Manage Your Coupons', path: '/apply-pms-coupon', role: 'PMS' },
    { title: 'Complaints', path: '/complaints', role: 'Admin' },
    { title: 'Reviews', path: '/all-reviews', role: 'Admin' },
    { title: 'Manage users', path: '/all-users', role: 'Admin' },
    { title: 'Bulk Operation', path: '/bulk-data-processing', role: 'Admin' },
    { title: 'Add travel location', path: '/add-travel-location', role: 'Admin' },
    { title: 'Partners', path: '/user', role: 'Admin' },
    { title: 'Availability', path: '/hotels/availability', role: 'Admin' },
    { title: 'Set Month', path: '/hotels/monthly-price', role: 'Admin' },
    { title: 'Change banner', path: '/change-banner', role: 'Admin' },
    { title: 'Apply Coupons (Single Use)', path: '/apply-coupon', role: 'Admin' },
    { title: 'Push notification', path: '/send-notification-to-all', role: 'Admin' },
];
